baseURL = "https://iamsorush.com/"
languageCode = "en-us"
title = "Sorush Khajepor - Numerical programming and app development"
theme = "blank"
RemovePathAccents = true
summaryLength = 25
pygmentsstyle = "monokai"
[Author]
  name = "Sorush Khajepor"
[params]
  myname="Sorush Khajepor"
  websitename="iamsorush.com"
  katex=false
  jqmath=false
[taxonomies]
    category = "categories"
    tag = "tags"
[markup.goldmark.renderer]
  unsafe= true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]