baseURL = "https://iamsorush.com/"
languageCode = "en-us"
title = "Sorush Khajepor - Numerical programming and app development"
theme = "blank"
summaryLength = 25
[Author]
  name = "Sorush Khajepor"
[params]
  myname="Sorush Khajepor"
  websitename="iamsorush.com"
  katex=false
[taxonomies]
    category = "categories"
    tag = "tags"
