[build]
    command = "gulp build:comments && hugo && npx netlify-lambda build ./functions"
    publish = "build/public"
    functions = "build/functions"
 
[context.production]
    command = "gulp build:comments && hugo && npx netlify-lambda build ./functions"
    functions = "build/functions"
    [context.production.environment]
        HUGO_VERSION = "0.48"
        HUGO_ENV = "production"
